### ISSUE TITLE
Java 9+ compatibility

### ISSUE THREAD

**Issue by Cybermaxke** [KyoriPowered/lambda#2]
You are currently reflecting into `MethodHandles.Lookup` to create private lookups which won't be possible by default in future java versions (will already throw illegal access messages). An easy solution is to use the new `MethodHandles#privateLookupIn` method when available (since Java 9).

https://github.com/KyoriPowered/lambda/blob/master/src/main/java/net/kyori/lambda/reflect/MoreMethodHandles.java#L51
https://docs.oracle.com/javase/9/docs/api/java/lang/invoke/MethodHandles.html#privateLookupIn-java.lang.Class-java.lang.invoke.MethodHandles.Lookup-

**Comment by kashike** [comment]
Yes, I'm aware. I plan to create a Java 9+ variant of lambda, I'm just not sure what to version it - 2.0.0?

**Comment by liach** [comment]
Should be 2. lunar's j9 version is version 2.

**Comment by kashike** [comment]
2.0.0-SNAPSHOT available.

**Comment by Cybermaxke** [comment]
Why not make the library compatible for all Java versions? Instead of multiple versions per Java version.

Another note: `MethodHandles.lookup()` is caller sensitive and provides access to the current class and module. The module access is required for the method `privateLookupIn` to allow private access across modules. So the `MethodHandles.lookup()` should be called from where `privateLookupIn` is called.
